# generated by datamodel-codegen:
#   filename:  aaaschema.json
#   timestamp: 2025-08-01T17:41:42+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, RootModel

from . import commons


class Cat(BaseModel):
    name: Optional[str] = None


class Dog(BaseModel):
    name: Optional[str] = None


class Animals(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    animals: Optional[commons.SmallArray] = None


class AllowedAnimals(RootModel[Union[Dog, Cat]]):
    model_config = ConfigDict(
        extra='forbid',
    )
    root: Union[Dog, Cat]
