# generated by datamodel-codegen:
#   filename:  bug.json
#   timestamp: 2025-08-01T17:07:08+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict


class Bug(BaseModel):
    bug_animals: Optional[Any] = None


class AllowedAnimals(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )
