# generated by datamodel-codegen:
#   filename:  commons.json
#   timestamp: 2025-08-01T17:07:08+00:00

from __future__ import annotations

from typing import Any, List

from pydantic import BaseModel, Field, RootModel


class Commons(RootModel[Any]):
    root: Any = Field(..., title='commons')


class MaxArray(RootModel[List]):
    root: List = Field(..., max_length=100)


class MinArray(RootModel[List]):
    root: List = Field(..., min_length=0)


class SmallArray(BaseModel):
    pass
